project:
  type: website

website:
  title: "aws-mle-associate-engineer-certification"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



