project:
  type: website
  output-dir: docs  # GitHub Pages will serve from the 'docs/' folder

website:
  title: "AWS Machine Learning Associate Certification"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: aws-mla-exam-resources.qmd
        text: Exam Resources
      - href: aws-definitions.qmd
        text: AWS Services Definitions
      - href: aws-comparison-tables.qmd
        text: AWS Comparisons Table
      - text: "Examples"
        menu:
          - text: "Apache Flink vs Kinesis Data Analytics"
            href: examples/flink-vs-kinesis.qmd
          - text: "Data Formats"
            href: examples/data-formats.qmd
          - text: "Storage: S3 vs EFS vs FSx vs EBS"
            href: examples/storage.qmd
          - text: "Streaming: Kinesis Data Streams vs Data Firehose vs Managed Service Kafka vs AMAA"
            href: examples/datastreams.qmd
          - text: "Glue Data Catalog vs Glue DataBrew vs Glue Studio"
            href: examples/glue.qmd
          - text: "Kendra vs OpenSearch"
            href: examples/search.qmd
          - text: "EMR vs Hadoop vs Spark"
            href: examples/emr-vs-hadoop-vs-spark.qmd
          - text: "Architecting Data: Warehouse, Lakes and Lakehouses"
            href: examples/data-architecture.qmd
          - text: "Glue and Athena"
            href: examples/glue-athena.qmd
          - text: "AWS Search"
            href: examples/search.qmd          
      - text: "Sagemaker"
        menu:
          - text: "SageMaker Pipelines"
            href: sagemaker/sagemaker-pipelines.qmd
          - text: "SageMaker for Model Building and Deployment"
            href: sagemaker/sagemaker-model-building-and-deployment.qmd
          - text: "SageMaker: Validating, Labelling and Mitigating Bias"
            href: sagemaker/sagemaker-validating-labelling-mitigating-bias.qmd
          - text: "Choosing and Integrating ML Models with AWS SageMaker"
            href: sagemaker/sagemaker-choosing-and-integrating-ml-models.qmd
          - text: "Advanced Machine Learning with AWS SageMaker"
            href: sagemaker/sagemaker-model-deployment-and-monitoring.qmd
          - text: "Multi-Model and Multi-Container Deployments on AWS"
            href: sagemaker/sagemaker-multi-model-multi-container-deployments.qmd
          - text: "Deploying and Monitoring SageMaker Models in a VPC"
            href: sagemaker/sagemaker-deploying-and-monitoring-models-in-vpc.qmd
          - text: "Optimizing SageMaker Deployments: Rightsizing, Cost Optimization, and Security"
            href: sagemaker/sagemaker-optimizing-deployments.qmd
          - text: "AI/ML: SageMaker vs Bedrock"
            href: sagemaker/sagemaker-vs-bedrock.qmd
      - text: "Practice Questions"
        menu:
          - text: "Practice Questions 1"
            href: practice/practice-questions-1.qmd
          - text: "Practice Questions 2"
            href: practice/practice-questions-2.qmd
          - text: "Practice Questions 3"
            href: practice/practice-questions-3.qmd
          - text: "Practice Questions 4"
            href: practice/practice-questions-4.qmd
          - text: "Practice Questions 5"
            href: practice/practice-questions-5.qmd
          - text: "Practice Questions 6"
            href: practice/practice-questions-6.qmd

format:
  html:
    theme: sketchy